[build]
  command = "yarn rw deploy netlify"
  publish = "web/dist"
  functions = "api/dist/functions"

[build.environment]
  OWM_ID = "own-id"

[dev]
  command = "yarn rw dev"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
